openapi: 3.0.0
info:
  title: TaraCDO — Explore. Discover. Experience
  description: Tourist Resource Locator API for establishments in Cagayan de Oro City.
  version: 1.0.0
  contact:
    name: TaraCDO
    url: https://github.com/GlavineLayo/-itcc14-api-project-TaraCDO-

servers:
  - url: http://devapi.com
  - url: https://prodapi.com

paths:

  /establishments:
    get:
      summary: Get all establishments
      description: Returns a list of all tourist establishments.
      responses:
        200:
          description: List of establishments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Establishment"

    post:
      summary: Add a new establishment
      description: Creates a new tourist establishment entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstablishmentInput"
      responses:
        201:
          description: Establishment successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Establishment"

  /establishments/{id}:
    get:
      summary: Get a specific establishment
      description: Retrieves info for one establishment by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Establishment record
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Establishment"
        404:
          description: Establishment not found

    put:
      summary: Update an establishment
      description: Updates an existing establishment record.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstablishmentInput"
      responses:
        200:
          description: Establishment successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Establishment"
        404:
          description: Establishment not found

    delete:
      summary: Delete an establishment
      description: Removes an establishment from the database.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Establishment successfully deleted
        404:
          description: Establishment not found

components:
  schemas:

    Establishment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Ayala Centrio Mall
        category:
          type: string
          example: "Mall"
        description:
          type: string
          example: "A popular shopping mall located in the heart of CDO."
        latitude:
          type: number
          example: 8.4825
        longitude:
          type: number
          example: 124.6472
        rating:
          type: number
          example: 4.5
        price_range:
          type: string
          example: "$$"
        address:
          type: string
          example: "C.M. Recto Avenue, Cagayan de Oro City"

    EstablishmentInput:
      type: object
      required:
        - name
        - category
        - latitude
        - longitude
      properties:
        name:
          type: string
          example: Ayala Centrio Mall
        category:
          type: string
          example: "Mall"
        description:
          type: string
          example: "A popular shopping mall located in the heart of CDO."
        latitude:
          type: number
          example: 8.4825
        longitude:
          type: number
          example: 124.6472
        rating:
          type: number
          example: 4.5
        price_range:
          type: string
          example: "$$"
        address:
          type: string
          example: "C.M. Recto Avenue, Cagayan de Oro City"
